version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.23.0
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: eslint-utils
    versions:
    - 1.4.3
  - dependency-name: acorn
    versions:
    - 5.7.4
